#!/bin/bash

# This script was auto-generated by generate_render_commands.py
# It contains commands to render videos for specific cases and timestamps.

echo "Starting batch rendering..."

python v_from_d.py --case_name single_push_rope --timestamp 20250528_123347
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123405
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123245
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123330
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123356
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123313
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123254
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123321
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123303
python v_from_d.py --case_name single_push_rope --timestamp 20250528_123338

echo "Batch rendering complete."
