#!/bin/bash

# This script was auto-generated by generate_render_commands.py
# It contains commands to render videos for specific cases and timestamps.

echo "Starting batch rendering..."

python v_from_d.py --case_name single_push_rope --timestamp 20250521_185250
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185207
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185215
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185233
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185308
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185158
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185241
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185224
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185150
python v_from_d.py --case_name single_push_rope --timestamp 20250521_185259

echo "Batch rendering complete."
