dataset:
  folder: "data/gnn_dyn_data_custom" # gen_data
  init_pos: 'spread'
  # initialization options:
  # - 'spread': deterministic spreaded object pile
  # - 'rand_blob': random blob-shape object pile
  # - 'rand_spread': random spreaded object pile
  # - 'rand_sparse_spread': random sparse spreaded object pile
  global_scale: 24
  n_episode: 500
  n_timestep: 80
  obj: "carrots"
  particle_r: 0.125
  cam_idx: 0
  wkspc_w: 5.0
  headless: True
  cont_motion: False
  robot_type: 'franka' # kinova; franka
  randomness: 
    use: True
    state_noise:
      train: 0.001
      valid: 0.0
  downsample_dist: 0.014

train:
  data_root: "../PhysTwin/generated_data"
  random_seed: 42
  n_epoch: 300
  lr: 0.001
  adam_beta1: 0.9
  batch_size: 64
  nf_hidden: 64
  num_workers: 12
  train_valid_ratio: 0.9
  log_per_iter: 50
  ckp_per_iter: 1000
  resume_epoch: -1
  resume_iter: -1
  n_history: 1
  n_rollout: 5
  rollout_decay: 1.0
  lr_scheduler:
    type: "StepLR"
    enabled: True
    step_size: 100
    gamma: 0.1 # reduce LR by this factor
    factor: 0.1 # ReduceLROnPlateau
    patience: 10 # ReduceLROnPlateau
    threshold_mode: 'rel' # ReduceLROnPlateau
    cooldown: 0 # ReduceLROnPlateau
  particle:
    nf_effect: 64
    resume:
      active: true
      epoch: 199
      iter: 0
      folder: 'N(0, 0.005) noise (copy)'
    adj_thresh: 0.05
    add_delta: False
    connect_tools_all: True  # Connect all tool particles to all object particles regardless of distance
    topk: 10  # Maximum number of neighbors per particle
  lam_reg: 2e-4
  lam_sp: 1e-2
  fps_radius: 0.02
