data_file: "PhysTwin/generated_data/mixed_push_rope.h5"
action_dim: 3
planner_type: "MPPI"           # Options: "MPPI", "GD", "MPPI_GD"
n_sample: 10                  # Number of action trajectories to sample
n_look_ahead: 10              # Number of steps to look ahead
n_update_iter: 5            # Number of optimization iterations
reward_weight: 100.0            # Temperature parameter for MPPI softmax
noise_level: 0.01              # Standard deviation for action noise
  
# Action Space Configuration
action_lower_bound: -0.05       # Lower bound for robot actions (m)
action_upper_bound: 0.05        # Upper bound for robot actions (m)
  
# Optimization Parameters
lr: 0.001                      # Learning rate for gradient descent (if using GD)
verbose: true                 # Enable detailed logging during optimization

# Reward Function Configuration
action_weight: 0              # Weight for action penalty in reward function