dataset:
  file: "PhysTwin/generated_data/lift_push_sampled_12_edges.h5"
  init_pos: 'spread'
  # initialization options:
  # - 'spread': deterministic spreaded object pile
  # - 'rand_blob': random blob-shape object pile
  # - 'rand_spread': random spreaded object pile
  # - 'rand_sparse_spread': random sparse spreaded object pile
  global_scale: 24
  n_episode: 6000
  n_timestep: 60
  obj: "carrots"
  particle_r: 0.125
  cam_idx: 0
  wkspc_w: 5.0
  headless: True
  cont_motion: False
  robot_type: 'franka' # kinova; franka
  randomness: 
    use: True
    state_noise:
      train: 0.002
      valid: 0.0
  downsample_rate: 3

train:
  random_seed: 42
  n_epoch: 150
  lr: 0.001
  adam_beta1: 0.9
  batch_size: 512
  nf_hidden: 80
  num_workers: 10
  train_valid_ratio: 0.9
  log_per_iter: 350
  ckp_per_iter: 1000
  n_history: 4
  n_rollout: 4
  rollout_decay: 1.0
  dropout_rate: 0.0
  lr_scheduler:
    type: "ReduceLROnPlateau"
    enabled: true
    step_size: 100 # StepLR
    gamma: 0.1 # StepLR
    factor: 0.2 # ReduceLROnPlateau
    patience: 10 # ReduceLROnPlateau
    threshold_mode: 'rel' # ReduceLROnPlateau
    cooldown: 0 # ReduceLROnPlateau
    min_lr: 0.000008 # ReduceLROnPlateau
  rollback:
    enabled: false
    patience: 8
    threshold: 1.7
  particle:
    nf_effect: 80
    fps_radius: 0.02
  resume:
    active: false
    epoch: 5
    iter: 0
    folder: "lift_push_1"
  edges:
    topological: 
      enabled: true
      adj_thresh: 0.09
      topk: 12
    collision:  
      adj_thresh: 0.06
      topk: 12
      connect_tools_all: False
  lam_reg: 2e-4
  lam_sp: 1e-2
