dataset:
  file: "PhysTwin/generated_data/sampled_with_edges.h5"
  init_pos: 'spread'
  # initialization options:
  # - 'spread': deterministic spreaded object pile
  # - 'rand_blob': random blob-shape object pile
  # - 'rand_spread': random spreaded object pile
  # - 'rand_sparse_spread': random sparse spreaded object pile
  global_scale: 24
  n_episode: 3000
  n_timestep: 60
  obj: "carrots"
  particle_r: 0.125
  cam_idx: 0
  wkspc_w: 5.0
  headless: True
  cont_motion: False
  robot_type: 'franka' # kinova; franka
  randomness: 
    use: False
    state_noise:
      train: 0.0
      valid: 0.0
  downsample_rate: 3

train:
  random_seed: 42
  n_epoch: 10
  lr: 0.001
  adam_beta1: 0.9
  batch_size: 128
  nf_hidden: 64
  num_workers: 10
  train_valid_ratio: 0.9
  log_per_iter: 350
  ckp_per_iter: 1000
  n_history: 4
  n_rollout: 4
  rollout_decay: 1.0
  lr_scheduler:
    type: "ReduceLROnPlateau"
    enabled: true
    step_size: 100 # StepLR
    gamma: 0.1 # StepLR
    factor: 0.2 # ReduceLROnPlateau
    patience: 10 # ReduceLROnPlateau
    threshold_mode: 'rel' # ReduceLROnPlateau
    cooldown: 0 # ReduceLROnPlateau
  rollback:
    enabled: true
    patience: 10
    threshold: 2
  particle:
    nf_effect: 64
    fps_radius: 0.02
  resume:
    active: false
    epoch: 28
    iter: 0
    folder: "test_no_edges"
  edges:
    topological: 
      enabled: true
      adj_thresh: 0.10
      topk: 10
    collision:  
      adj_thresh: 0.10
      topk: 15 
      connect_tools_all: False
  lam_reg: 2e-4
  lam_sp: 1e-2
